name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      lint_fix:
        description: "lint:fix"
        required: false
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LINT_FIX: ${{ fromJSON(inputs.lint_fix || 'false') || github.event_name == 'pull_request' && github.head_ref != 'main' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install pnpm
        run: |
          npm i -g pnpm
          pnpm -v
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
      - run: pnpm install
      - run: pnpm typecheck
      - run: pnpm lint
        if: ${{ ! fromJSON(env.LINT_FIX) }}
      - run: pnpm lint:fix
        if: ${{ fromJSON(env.LINT_FIX) }}
      - name: Commit linter fixes
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 #v5
        if: ${{ fromJSON(env.LINT_FIX) }}
        with:
          commit_message: "automated commit: pnpm lint:fix"
